name: Build and deploy

on:
  push:
    branches: [ "master" ]
    paths: 
    - "dist/"
    - "posts/"
    - "raw/"
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Upload artifact
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    # - run: npm install -g yarn # Extra Step
    # - name: Build
      # run: |
        # yarn
        # yarn build
    # - name: Generate
      # run: yarn generate
    - name: Package
      run: |
        mkdir _site
        mv ./dist/* ./posts ./raw  ./_site/
    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v2
      with:
        # upload entire directory
        path: './_site'
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v3